apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "virtrigaud.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "virtrigaud.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
data:
  config.yaml: |
    # Virtrigaud Manager Configuration
    manager:
      # Worker configuration
      workers:
        perKind: {{ .Values.config.workers.perKind }}
        maxInflightTasks: {{ .Values.config.workers.maxInflightTasks }}
      
      # Feature gates
      {{- if .Values.config.featureGates }}
      featureGates:
        {{- range .Values.config.featureGates }}
        - {{ . }}
        {{- end }}
      {{- end }}
      
      # RBAC scope
      rbac:
        scope: {{ .Values.rbac.scope }}
    
    # Retry configuration
    retry:
      maxAttempts: {{ .Values.config.retry.maxAttempts }}
      baseDelay: {{ .Values.config.retry.baseDelay }}
      maxDelay: {{ .Values.config.retry.maxDelay }}
    
    # Circuit breaker configuration
    circuitBreaker:
      failureThreshold: {{ .Values.config.circuitBreaker.failureThreshold }}
      resetTimeout: {{ .Values.config.circuitBreaker.resetTimeout }}
    
    # Rate limiting configuration
    rateLimit:
      qps: {{ .Values.config.rateLimit.qps }}
      burst: {{ .Values.config.rateLimit.burst }}
    
    # TLS configuration
    tls:
      enabled: {{ .Values.security.tls.enabled }}
      mTLS: {{ .Values.security.tls.mTLS }}
      {{- if .Values.security.tls.enabled }}
      {{- if eq .Values.security.tls.source "manual" }}
      managerSecret: {{ .Values.security.tls.secrets.manager }}
      providerSecret: {{ .Values.security.tls.secrets.providers }}
      {{- end }}
      {{- end }}
    
    # Observability configuration
    observability:
      prometheus:
        enabled: {{ .Values.observability.prometheus.enabled }}
      tracing:
        enabled: {{ .Values.observability.tracing.enabled }}
        {{- if .Values.observability.tracing.enabled }}
        endpoint: {{ .Values.observability.tracing.endpoint | quote }}
        samplingRatio: {{ .Values.observability.tracing.samplingRatio }}
        {{- end }}
    
    # Provider configuration
    providers:
      libvirt:
        enabled: {{ .Values.providers.libvirt.enabled }}
        {{- if .Values.providers.libvirt.enabled }}
        remote:
          enabled: {{ .Values.providers.libvirt.remote.enabled }}
          {{- if .Values.providers.libvirt.remote.enabled }}
          endpoint: {{ include "virtrigaud.fullname" . }}-provider-libvirt:9443
          {{- end }}
        {{- end }}
      vsphere:
        enabled: {{ .Values.providers.vsphere.enabled }}
        {{- if .Values.providers.vsphere.enabled }}
        remote:
          enabled: {{ .Values.providers.vsphere.remote.enabled }}
          {{- if .Values.providers.vsphere.remote.enabled }}
          endpoint: {{ include "virtrigaud.fullname" . }}-provider-vsphere:9443
          {{- end }}
        {{- end }}
    
    # Webhook configuration
    webhooks:
      enabled: {{ .Values.webhooks.enabled }}
      conversion:
        enabled: {{ .Values.webhooks.conversion.enabled }}
      validating:
        enabled: {{ .Values.webhooks.validating.enabled }}
        failurePolicy: {{ .Values.webhooks.validating.failurePolicy }}
      mutating:
        enabled: {{ .Values.webhooks.mutating.enabled }}
        failurePolicy: {{ .Values.webhooks.mutating.failurePolicy }}
