apiVersion: infra.virtrigaud.io/v1alpha1
kind: VirtualMachine
metadata:
  name: demo-web-01
  namespace: default
  labels:
    app: demo-web
    environment: staging
spec:
  providerRef:
    name: vsphere-prod
    namespace: default
  classRef:
    name: medium
  imageRef:
    name: ubuntu-22-template
  networks:
    - name: app-net
      ipPolicy: dhcp
    - name: mgmt-net
      ipPolicy: static
      staticIP: 192.168.1.100
  disks:
    - name: data-disk
      sizeGiB: 100
      type: thin
  userData:
    cloudInit:
      inline: |
        #cloud-config
        hostname: demo-web-01
        users:
          - name: ubuntu
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7...
  placement:
    cluster: prod-cluster-01
    datastore: vsanDatastore
    folder: "/Demo/WebServers"
  powerState: "On"
  tags:
    - demo
    - web-server
    - staging
  resources:
    cpu: 4
    memoryMiB: 8192
    gpu:
      count: 1
      type: nvidia-t4
      memory: 16384
  placementRef:
    name: web-placement-policy
  snapshot:
    revertToRef:
      name: pre-update-snapshot
