apiVersion: infra.virtrigaud.io/v1alpha1
kind: VirtualMachine
metadata:
  name: demo-web-01
  namespace: default
spec:
  providerRef:
    name: vsphere-prod
  classRef:
    name: small
  imageRef:
    name: ubuntu-22-template
  networks:
    - name: app-net
      ipPolicy: dhcp
  disks:
    - sizeGiB: 50
      type: thin
      name: data-disk
  powerState: On
  userData:
    cloudInit:
      inline: |
        #cloud-config
        packages:
          - nginx
        runcmd:
          - [ systemctl, enable, --now, nginx ]
        users:
          - name: ubuntu
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC... # Add your SSH key here
  tags:
    - environment:demo
    - application:web
