# golangci-lint configuration for VirtRigaud
version: 2

run:
  timeout: 10m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - misspell
    - unconvert

linters-settings:
  staticcheck:
    checks: ["all"]
  errcheck:
    check-type-assertions: true
    check-blank: false