# golangci-lint configuration for VirtRigaud
# Compatible with golangci-lint v2.4.0+

run:
  timeout: 5m
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - gosimple
    - unused
    - typecheck
    - errcheck
    - misspell
    - unconvert
  disable:
    - gosec
    - gocritic
    - unparam
    - prealloc

linters-settings:
  staticcheck:
    checks: ["all"]
  errcheck:
    check-type-assertions: true
    check-blank: false