run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - typecheck

linters-settings:
  revive:
    confidence: 0
  goimports:
    local-prefixes: github.com/projectbeskar/virtrigaud

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - revive
        - staticcheck
    # Exclude generated files
    - path: ".*\\.pb\\.go$"
      linters:
        - revive
        - staticcheck
        - unused
    # Exclude kubebuilder generated files
    - path: "zz_generated.*\\.go$"
      linters:
        - revive
        - staticcheck
        - unused