run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - internal/providers/libvirt
    - cmd/provider-libvirt

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - errcheck
    - gosimple
  disable:
    - typecheck  # Disabled due to libvirt CGO dependencies that aren't available in CI

linters-settings:
  revive:
    confidence: 0
  goimports:
    local-prefixes: github.com/projectbeskar/virtrigaud

issues:
  exclude-dirs:
    - internal/providers/libvirt
    - cmd/provider-libvirt
  exclude-files:
    - "internal/providers/libvirt/.*\\.go$"
    - "cmd/provider-libvirt/.*\\.go$"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - revive
        - staticcheck
    # Exclude generated files
    - path: ".*\\.pb\\.go$"
      linters:
        - revive
        - staticcheck
        - unused
    # Exclude kubebuilder generated files
    - path: "zz_generated.*\\.go$"
      linters:
        - revive
        - staticcheck
        - unused
    # Exclude libvirt provider entirely (requires C dependencies)
    - path: "internal/providers/libvirt/.*"
      linters:
        - typecheck
        - gosimple
        - unused
        - staticcheck
        - ineffassign
        - govet
        - errcheck
        - revive
        - gofmt
        - goimports
        - misspell
    - path: "cmd/provider-libvirt/.*"
      linters:
        - typecheck
        - gosimple
        - unused
        - staticcheck
        - ineffassign
        - govet
        - errcheck
        - revive
        - gofmt
        - goimports
        - misspell
    # Exclude libvirt files completely (alternative approach)
    - path: ".*/libvirt/.*"
      text: ".*"
    - path: ".*libvirt.*"
      text: ".*"
    # Exclude integration tests (may have libvirt dependencies)
    - path: "test/integration/.*"
      linters:
        - typecheck
        - gosimple
        - unused
        - staticcheck
        - ineffassign
        - govet
        - errcheck
        - revive
        - gofmt
        - goimports
        - misspell