apiVersion: infra.virtrigaud.io/v1beta1
kind: VirtualMachine
metadata:
  name: demo-web-01
  namespace: default
  labels:
    app: demo-web
    environment: demo
spec:
  providerRef:
    name: vsphere-prod
  classRef:
    name: small
  imageRef:
    name: ubuntu-22-template
  networks:
    - name: app-net
      networkRef:
        name: app-network
      ipAddress: ""  # Empty for DHCP
  storage:
    disks:
      - name: data-disk
        size: 50Gi
        type: thin
  userData:
    cloudInit:
      inline: |
        #cloud-config
        packages:
          - nginx
        runcmd:
          - [ systemctl, enable, --now, nginx ]
        users:
          - name: ubuntu
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC... # Add your SSH key here
  powerState: On
  metadata:
    labels:
      environment: demo
      application: web
