apiVersion: v1
kind: Secret
metadata:
  name: vsphere-creds
  namespace: default
type: Opaque
stringData:
  username: "svc-virtrigaud"
  password: "REDACTED"
  # Alternatively, you can use a token:
  # token: "your-vsphere-api-token"
