apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "virtrigaud-provider-runtime.fullname" . }}
  labels:
    {{- include "virtrigaud-provider-runtime.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "virtrigaud-provider-runtime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "virtrigaud-provider-runtime.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "virtrigaud-provider-runtime.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: provider
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 9443
              protocol: TCP
            - name: health
              containerPort: 8080
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- include "virtrigaud-provider-runtime.env" . | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- if .Values.livenessProbe.grpc }}
            grpc:
              port: {{ .Values.livenessProbe.grpc.port }}
            {{- else }}
            httpGet:
              path: /health
              port: health
            {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            {{- if .Values.readinessProbe.grpc }}
            grpc:
              port: {{ .Values.readinessProbe.grpc.port }}
            {{- else }}
            httpGet:
              path: /ready
              port: health
            {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "virtrigaud-provider-runtime.tlsVolumeMounts" . | nindent 12 }}
            {{- include "virtrigaud-provider-runtime.credentialsVolumeMounts" . | nindent 12 }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- include "virtrigaud-provider-runtime.tlsVolumes" . | nindent 8 }}
        {{- include "virtrigaud-provider-runtime.credentialsVolumes" . | nindent 8 }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
