{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "virtrigaud-provider-runtime.fullname" . }}
  labels:
    {{- include "virtrigaud-provider-runtime.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "virtrigaud-provider-runtime.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.ingress.fromNamespaces }}
    {{- range .Values.networkPolicy.ingress.fromNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ . }}
      ports:
        - protocol: TCP
          port: 9443
        - protocol: TCP
          port: 8080
    {{- end }}
    {{- else }}
    - from: []
      ports:
        - protocol: TCP
          port: 9443
        - protocol: TCP
          port: 8080
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.egress }}
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
    {{- else }}
    # Allow all egress by default
    - {}
    {{- end }}
{{- end }}
