# This rule is not used by the project virtrigaud itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over infra.virtrigaud.io.infra.virtrigaud.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: virtrigaud
    app.kubernetes.io/managed-by: kustomize
  name: vmimage-admin-role
rules:
- apiGroups:
  - infra.virtrigaud.io.infra.virtrigaud.io
  resources:
  - vmimages
  verbs:
  - '*'
- apiGroups:
  - infra.virtrigaud.io.infra.virtrigaud.io
  resources:
  - vmimages/status
  verbs:
  - get
