apiVersion: v1
kind: Secret
metadata:
  name: libvirt-creds
  namespace: default
type: Opaque
stringData:
  # For SASL authentication (if required)
  username: "virtrigaud"
  password: "REDACTED"
  # For TLS client certificates (if required)
  # tls.crt: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----
  # tls.key: |
  #   -----BEGIN PRIVATE KEY-----
  #   ...
  #   -----END PRIVATE KEY-----
