apiVersion: infra.virtrigaud.io/v1beta1
kind: VirtualMachine
metadata:
  name: demo-web-01
  namespace: default
  labels:
    app: demo-web
    environment: staging
spec:
  providerRef:
    name: vsphere-prod
    namespace: default
  classRef:
    name: medium
  imageRef:
    name: ubuntu-22-template
  networks:
    - name: app-net
      networkRef:
        name: app-network
        namespace: default
      ipAddress: ""  # Empty for DHCP
      macAddress: ""
    - name: mgmt-net
      networkRef:
        name: mgmt-network
        namespace: default
      ipAddress: "192.168.1.100"
      macAddress: "00:50:56:a1:b2:c3"
  disks:
    - name: data-disk
      sizeGiB: 100
      type: thin
      expandPolicy: Offline
      storageClass: fast-ssd
  userData:
    cloudInit:
      inline: |
        #cloud-config
        hostname: demo-web-01
        users:
          - name: ubuntu
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7...
    ignition: null
  placement:
    cluster: prod-cluster-01
    host: esxi-host-03.example.com
    datastore: vsanDatastore
    folder: "/Demo/WebServers"
    resourcePool: WebApps-RP
  powerState: On
  tags:
    - demo
    - web-server
    - staging
  resources:
    cpu: 4
    memoryMiB: 8192
    gpu:
      count: 1
      type: nvidia-t4
      memory: 16384
  placementRef:
    name: web-placement-policy
  snapshot:
    revertToRef:
      name: pre-update-snapshot
  lifecycle:
    preStop:
      exec:
        command: ["/opt/app/shutdown.sh"]
    postStart:
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
    gracefulShutdownTimeout: 60s
