apiVersion: infra.virtrigaud.io/v1beta1
kind: Provider
metadata:
  name: libvirt-local
  namespace: default
spec:
  type: libvirt
  endpoint: qemu+tcp://libvirt.example.com/system
  credentialSecretRef:
    name: libvirt-creds
  defaults:
    cluster: default
  rateLimit:
    qps: 5
    burst: 10
