apiVersion: infra.virtrigaud.io/v1alpha1
kind: VMNetworkAttachment
metadata:
  name: app-net
  namespace: default
spec:
  ipPolicy: dhcp
  vsphere:
    portgroup: "PG-App"
  libvirt:
    networkName: "default"
    model: virtio
