# Example secrets for Proxmox VE Provider
# DO NOT commit actual credentials to version control

# API Token credentials (recommended)
apiVersion: v1
kind: Secret
metadata:
  name: pve-credentials
  namespace: virtrigaud-system
type: Opaque
stringData:
  # API Token format: USER@REALM!TOKENID=SECRET
  token_id: "virtrigaud@pve!vrtg-token"
  token_secret: "xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx"
  
  # Optional: Custom CA certificate for self-signed Proxmox VE
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkWgAwIBAgIJAL...
    [Your Proxmox VE CA certificate here]
    ...
    -----END CERTIFICATE-----

---
# Alternative: Username/password authentication (less secure)
apiVersion: v1
kind: Secret
metadata:
  name: pve-credentials-userpass
  namespace: virtrigaud-system
type: Opaque
stringData:
  username: "virtrigaud@pve"
  password: "secure-password-here"
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkWgAwIBAgIJAL...
    [Your Proxmox VE CA certificate here]
    ...
    -----END CERTIFICATE-----

---
# TLS certificates for provider gRPC endpoint
apiVersion: v1
kind: Secret
metadata:
  name: proxmox-provider-tls
  namespace: virtrigaud-system
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key
  tls.crt: LS0tLS1CRUdJTi... # Your TLS certificate
  tls.key: LS0tLS1CRUdJTi... # Your TLS private key

---
# External Secrets Operator example (if using ESO)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: virtrigaud-system
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "virtrigaud-role"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pve-credentials-external
  namespace: virtrigaud-system
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: pve-credentials
    creationPolicy: Owner
  data:
  - secretKey: token_id
    remoteRef:
      key: proxmox/credentials
      property: token_id
  - secretKey: token_secret
    remoteRef:
      key: proxmox/credentials
      property: token_secret
  - secretKey: ca.crt
    remoteRef:
      key: proxmox/certificates
      property: ca_cert
