// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: provider/v1/provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Power operations enum
type PowerOp int32

const (
	PowerOp_POWER_OP_UNSPECIFIED PowerOp = 0
	PowerOp_POWER_OP_ON          PowerOp = 1
	PowerOp_POWER_OP_OFF         PowerOp = 2
	PowerOp_POWER_OP_REBOOT      PowerOp = 3
)

// Enum value maps for PowerOp.
var (
	PowerOp_name = map[int32]string{
		0: "POWER_OP_UNSPECIFIED",
		1: "POWER_OP_ON",
		2: "POWER_OP_OFF",
		3: "POWER_OP_REBOOT",
	}
	PowerOp_value = map[string]int32{
		"POWER_OP_UNSPECIFIED": 0,
		"POWER_OP_ON":          1,
		"POWER_OP_OFF":         2,
		"POWER_OP_REBOOT":      3,
	}
)

func (x PowerOp) Enum() *PowerOp {
	p := new(PowerOp)
	*p = x
	return p
}

func (x PowerOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerOp) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[0].Descriptor()
}

func (PowerOp) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[0]
}

func (x PowerOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerOp.Descriptor instead.
func (PowerOp) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

// Task reference for async operations
type TaskRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRef) Reset() {
	*x = TaskRef{}
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRef) ProtoMessage() {}

func (x *TaskRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRef.ProtoReflect.Descriptor instead.
func (*TaskRef) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Empty message for operations with no parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

// Validate provider connectivity and configuration
type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Create a new virtual machine
type CreateRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserData []byte                 `protobuf:"bytes,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"` // Already rendered cloud-init/ignition data
	// JSON-encoded provider-agnostic specifications
	ClassJson     string   `protobuf:"bytes,3,opt,name=class_json,json=classJson,proto3" json:"class_json,omitempty"`             // VMClass
	ImageJson     string   `protobuf:"bytes,4,opt,name=image_json,json=imageJson,proto3" json:"image_json,omitempty"`             // VMImage
	NetworksJson  string   `protobuf:"bytes,5,opt,name=networks_json,json=networksJson,proto3" json:"networks_json,omitempty"`    // []NetworkAttachment
	DisksJson     string   `protobuf:"bytes,6,opt,name=disks_json,json=disksJson,proto3" json:"disks_json,omitempty"`             // []DiskSpec
	PlacementJson string   `protobuf:"bytes,7,opt,name=placement_json,json=placementJson,proto3" json:"placement_json,omitempty"` // Placement
	Tags          []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`                                        // Tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetUserData() []byte {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *CreateRequest) GetClassJson() string {
	if x != nil {
		return x.ClassJson
	}
	return ""
}

func (x *CreateRequest) GetImageJson() string {
	if x != nil {
		return x.ImageJson
	}
	return ""
}

func (x *CreateRequest) GetNetworksJson() string {
	if x != nil {
		return x.NetworksJson
	}
	return ""
}

func (x *CreateRequest) GetDisksJson() string {
	if x != nil {
		return x.DisksJson
	}
	return ""
}

func (x *CreateRequest) GetPlacementJson() string {
	if x != nil {
		return x.PlacementJson
	}
	return ""
}

func (x *CreateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // Provider-specific VM identifier
	Task          *TaskRef               `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"` // Optional task reference for async operations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateResponse) GetTask() *TaskRef {
	if x != nil {
		return x.Task
	}
	return nil
}

// Delete a virtual machine
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Power control operations
type PowerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Op            PowerOp                `protobuf:"varint,2,opt,name=op,proto3,enum=provider.v1.PowerOp" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerRequest) Reset() {
	*x = PowerRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerRequest) ProtoMessage() {}

func (x *PowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerRequest.ProtoReflect.Descriptor instead.
func (*PowerRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *PowerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PowerRequest) GetOp() PowerOp {
	if x != nil {
		return x.Op
	}
	return PowerOp_POWER_OP_UNSPECIFIED
}

// Reconfigure virtual machine resources
type ReconfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DesiredJson   string                 `protobuf:"bytes,2,opt,name=desired_json,json=desiredJson,proto3" json:"desired_json,omitempty"` // JSON-encoded desired state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconfigureRequest) Reset() {
	*x = ReconfigureRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconfigureRequest) ProtoMessage() {}

func (x *ReconfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconfigureRequest.ProtoReflect.Descriptor instead.
func (*ReconfigureRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ReconfigureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReconfigureRequest) GetDesiredJson() string {
	if x != nil {
		return x.DesiredJson
	}
	return ""
}

// Generic task response for async operations
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskRef               `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *TaskResponse) GetTask() *TaskRef {
	if x != nil {
		return x.Task
	}
	return nil
}

// Describe virtual machine current state
type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *DescribeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DescribeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Exists          bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	PowerState      string                 `protobuf:"bytes,2,opt,name=power_state,json=powerState,proto3" json:"power_state,omitempty"`
	Ips             []string               `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
	ConsoleUrl      string                 `protobuf:"bytes,4,opt,name=console_url,json=consoleUrl,proto3" json:"console_url,omitempty"`
	ProviderRawJson string                 `protobuf:"bytes,5,opt,name=provider_raw_json,json=providerRawJson,proto3" json:"provider_raw_json,omitempty"` // Provider-specific additional data
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *DescribeResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *DescribeResponse) GetPowerState() string {
	if x != nil {
		return x.PowerState
	}
	return ""
}

func (x *DescribeResponse) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *DescribeResponse) GetConsoleUrl() string {
	if x != nil {
		return x.ConsoleUrl
	}
	return ""
}

func (x *DescribeResponse) GetProviderRawJson() string {
	if x != nil {
		return x.ProviderRawJson
	}
	return ""
}

// Check async task status
type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskRef               `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *TaskStatusRequest) GetTask() *TaskRef {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message if task failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{13}
}

func (x *TaskStatusResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *TaskStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Snapshot operations
type SnapshotCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	NameHint      string                 `protobuf:"bytes,2,opt,name=name_hint,json=nameHint,proto3" json:"name_hint,omitempty"`
	IncludeMemory bool                   `protobuf:"varint,3,opt,name=include_memory,json=includeMemory,proto3" json:"include_memory,omitempty"` // Include memory state if supported
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotCreateRequest) Reset() {
	*x = SnapshotCreateRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotCreateRequest) ProtoMessage() {}

func (x *SnapshotCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotCreateRequest.ProtoReflect.Descriptor instead.
func (*SnapshotCreateRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{14}
}

func (x *SnapshotCreateRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SnapshotCreateRequest) GetNameHint() string {
	if x != nil {
		return x.NameHint
	}
	return ""
}

func (x *SnapshotCreateRequest) GetIncludeMemory() bool {
	if x != nil {
		return x.IncludeMemory
	}
	return false
}

func (x *SnapshotCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SnapshotCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Task          *TaskRef               `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotCreateResponse) Reset() {
	*x = SnapshotCreateResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotCreateResponse) ProtoMessage() {}

func (x *SnapshotCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotCreateResponse.ProtoReflect.Descriptor instead.
func (*SnapshotCreateResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *SnapshotCreateResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotCreateResponse) GetTask() *TaskRef {
	if x != nil {
		return x.Task
	}
	return nil
}

type SnapshotDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotDeleteRequest) Reset() {
	*x = SnapshotDeleteRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDeleteRequest) ProtoMessage() {}

func (x *SnapshotDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDeleteRequest.ProtoReflect.Descriptor instead.
func (*SnapshotDeleteRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{16}
}

func (x *SnapshotDeleteRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SnapshotDeleteRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type SnapshotRevertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRevertRequest) Reset() {
	*x = SnapshotRevertRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRevertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRevertRequest) ProtoMessage() {}

func (x *SnapshotRevertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRevertRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRevertRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{17}
}

func (x *SnapshotRevertRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SnapshotRevertRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

// Clone operations
type CloneRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SourceVmId string                 `protobuf:"bytes,1,opt,name=source_vm_id,json=sourceVmId,proto3" json:"source_vm_id,omitempty"`
	TargetName string                 `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	Linked     bool                   `protobuf:"varint,3,opt,name=linked,proto3" json:"linked,omitempty"` // Best-effort linked clone
	// JSON-encoded specifications for customization
	ClassJson     string `protobuf:"bytes,4,opt,name=class_json,json=classJson,proto3" json:"class_json,omitempty"`             // VMClass overrides
	PlacementJson string `protobuf:"bytes,5,opt,name=placement_json,json=placementJson,proto3" json:"placement_json,omitempty"` // Placement hints
	CustomizeJson string `protobuf:"bytes,6,opt,name=customize_json,json=customizeJson,proto3" json:"customize_json,omitempty"` // Customization spec
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{18}
}

func (x *CloneRequest) GetSourceVmId() string {
	if x != nil {
		return x.SourceVmId
	}
	return ""
}

func (x *CloneRequest) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *CloneRequest) GetLinked() bool {
	if x != nil {
		return x.Linked
	}
	return false
}

func (x *CloneRequest) GetClassJson() string {
	if x != nil {
		return x.ClassJson
	}
	return ""
}

func (x *CloneRequest) GetPlacementJson() string {
	if x != nil {
		return x.PlacementJson
	}
	return ""
}

func (x *CloneRequest) GetCustomizeJson() string {
	if x != nil {
		return x.CustomizeJson
	}
	return ""
}

type CloneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetVmId    string                 `protobuf:"bytes,1,opt,name=target_vm_id,json=targetVmId,proto3" json:"target_vm_id,omitempty"`
	Task          *TaskRef               `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneResponse) Reset() {
	*x = CloneResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneResponse) ProtoMessage() {}

func (x *CloneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneResponse.ProtoReflect.Descriptor instead.
func (*CloneResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{19}
}

func (x *CloneResponse) GetTargetVmId() string {
	if x != nil {
		return x.TargetVmId
	}
	return ""
}

func (x *CloneResponse) GetTask() *TaskRef {
	if x != nil {
		return x.Task
	}
	return nil
}

// Image preparation operations
type ImagePrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageJson     string                 `protobuf:"bytes,1,opt,name=image_json,json=imageJson,proto3" json:"image_json,omitempty"`       // JSON-encoded VMImage spec
	TargetName    string                 `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`    // Target template/image name
	StorageHint   string                 `protobuf:"bytes,3,opt,name=storage_hint,json=storageHint,proto3" json:"storage_hint,omitempty"` // Storage location hint (datastore, pool, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePrepareRequest) Reset() {
	*x = ImagePrepareRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePrepareRequest) ProtoMessage() {}

func (x *ImagePrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePrepareRequest.ProtoReflect.Descriptor instead.
func (*ImagePrepareRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{20}
}

func (x *ImagePrepareRequest) GetImageJson() string {
	if x != nil {
		return x.ImageJson
	}
	return ""
}

func (x *ImagePrepareRequest) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *ImagePrepareRequest) GetStorageHint() string {
	if x != nil {
		return x.StorageHint
	}
	return ""
}

// Capability check - what features does this provider support
type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{21}
}

type GetCapabilitiesResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	SupportsReconfigureOnline   bool                   `protobuf:"varint,1,opt,name=supports_reconfigure_online,json=supportsReconfigureOnline,proto3" json:"supports_reconfigure_online,omitempty"`
	SupportsDiskExpansionOnline bool                   `protobuf:"varint,2,opt,name=supports_disk_expansion_online,json=supportsDiskExpansionOnline,proto3" json:"supports_disk_expansion_online,omitempty"`
	SupportsSnapshots           bool                   `protobuf:"varint,3,opt,name=supports_snapshots,json=supportsSnapshots,proto3" json:"supports_snapshots,omitempty"`
	SupportsMemorySnapshots     bool                   `protobuf:"varint,4,opt,name=supports_memory_snapshots,json=supportsMemorySnapshots,proto3" json:"supports_memory_snapshots,omitempty"`
	SupportsLinkedClones        bool                   `protobuf:"varint,5,opt,name=supports_linked_clones,json=supportsLinkedClones,proto3" json:"supports_linked_clones,omitempty"`
	SupportsImageImport         bool                   `protobuf:"varint,6,opt,name=supports_image_import,json=supportsImageImport,proto3" json:"supports_image_import,omitempty"`
	SupportedDiskTypes          []string               `protobuf:"bytes,7,rep,name=supported_disk_types,json=supportedDiskTypes,proto3" json:"supported_disk_types,omitempty"`
	SupportedNetworkTypes       []string               `protobuf:"bytes,8,rep,name=supported_network_types,json=supportedNetworkTypes,proto3" json:"supported_network_types,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{22}
}

func (x *GetCapabilitiesResponse) GetSupportsReconfigureOnline() bool {
	if x != nil {
		return x.SupportsReconfigureOnline
	}
	return false
}

func (x *GetCapabilitiesResponse) GetSupportsDiskExpansionOnline() bool {
	if x != nil {
		return x.SupportsDiskExpansionOnline
	}
	return false
}

func (x *GetCapabilitiesResponse) GetSupportsSnapshots() bool {
	if x != nil {
		return x.SupportsSnapshots
	}
	return false
}

func (x *GetCapabilitiesResponse) GetSupportsMemorySnapshots() bool {
	if x != nil {
		return x.SupportsMemorySnapshots
	}
	return false
}

func (x *GetCapabilitiesResponse) GetSupportsLinkedClones() bool {
	if x != nil {
		return x.SupportsLinkedClones
	}
	return false
}

func (x *GetCapabilitiesResponse) GetSupportsImageImport() bool {
	if x != nil {
		return x.SupportsImageImport
	}
	return false
}

func (x *GetCapabilitiesResponse) GetSupportedDiskTypes() []string {
	if x != nil {
		return x.SupportedDiskTypes
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetSupportedNetworkTypes() []string {
	if x != nil {
		return x.SupportedNetworkTypes
	}
	return nil
}

var File_provider_v1_provider_proto protoreflect.FileDescriptor

const file_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1aprovider/v1/provider.proto\x12\vprovider.v1\"\x19\n" +
	"\aTaskRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty\"\x11\n" +
	"\x0fValidateRequest\"<\n" +
	"\x10ValidateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfd\x01\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tuser_data\x18\x02 \x01(\fR\buserData\x12\x1d\n" +
	"\n" +
	"class_json\x18\x03 \x01(\tR\tclassJson\x12\x1d\n" +
	"\n" +
	"image_json\x18\x04 \x01(\tR\timageJson\x12#\n" +
	"\rnetworks_json\x18\x05 \x01(\tR\fnetworksJson\x12\x1d\n" +
	"\n" +
	"disks_json\x18\x06 \x01(\tR\tdisksJson\x12%\n" +
	"\x0eplacement_json\x18\a \x01(\tR\rplacementJson\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\"J\n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04task\x18\x02 \x01(\v2\x14.provider.v1.TaskRefR\x04task\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\fPowerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x02op\x18\x02 \x01(\x0e2\x14.provider.v1.PowerOpR\x02op\"G\n" +
	"\x12ReconfigureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdesired_json\x18\x02 \x01(\tR\vdesiredJson\"8\n" +
	"\fTaskResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.provider.v1.TaskRefR\x04task\"!\n" +
	"\x0fDescribeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaa\x01\n" +
	"\x10DescribeResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1f\n" +
	"\vpower_state\x18\x02 \x01(\tR\n" +
	"powerState\x12\x10\n" +
	"\x03ips\x18\x03 \x03(\tR\x03ips\x12\x1f\n" +
	"\vconsole_url\x18\x04 \x01(\tR\n" +
	"consoleUrl\x12*\n" +
	"\x11provider_raw_json\x18\x05 \x01(\tR\x0fproviderRawJson\"=\n" +
	"\x11TaskStatusRequest\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.provider.v1.TaskRefR\x04task\">\n" +
	"\x12TaskStatusResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x92\x01\n" +
	"\x15SnapshotCreateRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1b\n" +
	"\tname_hint\x18\x02 \x01(\tR\bnameHint\x12%\n" +
	"\x0einclude_memory\x18\x03 \x01(\bR\rincludeMemory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"c\n" +
	"\x16SnapshotCreateResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12(\n" +
	"\x04task\x18\x02 \x01(\v2\x14.provider.v1.TaskRefR\x04task\"M\n" +
	"\x15SnapshotDeleteRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"M\n" +
	"\x15SnapshotRevertRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"\xd6\x01\n" +
	"\fCloneRequest\x12 \n" +
	"\fsource_vm_id\x18\x01 \x01(\tR\n" +
	"sourceVmId\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x01(\tR\n" +
	"targetName\x12\x16\n" +
	"\x06linked\x18\x03 \x01(\bR\x06linked\x12\x1d\n" +
	"\n" +
	"class_json\x18\x04 \x01(\tR\tclassJson\x12%\n" +
	"\x0eplacement_json\x18\x05 \x01(\tR\rplacementJson\x12%\n" +
	"\x0ecustomize_json\x18\x06 \x01(\tR\rcustomizeJson\"[\n" +
	"\rCloneResponse\x12 \n" +
	"\ftarget_vm_id\x18\x01 \x01(\tR\n" +
	"targetVmId\x12(\n" +
	"\x04task\x18\x02 \x01(\v2\x14.provider.v1.TaskRefR\x04task\"x\n" +
	"\x13ImagePrepareRequest\x12\x1d\n" +
	"\n" +
	"image_json\x18\x01 \x01(\tR\timageJson\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x01(\tR\n" +
	"targetName\x12!\n" +
	"\fstorage_hint\x18\x03 \x01(\tR\vstorageHint\"\x18\n" +
	"\x16GetCapabilitiesRequest\"\xdd\x03\n" +
	"\x17GetCapabilitiesResponse\x12>\n" +
	"\x1bsupports_reconfigure_online\x18\x01 \x01(\bR\x19supportsReconfigureOnline\x12C\n" +
	"\x1esupports_disk_expansion_online\x18\x02 \x01(\bR\x1bsupportsDiskExpansionOnline\x12-\n" +
	"\x12supports_snapshots\x18\x03 \x01(\bR\x11supportsSnapshots\x12:\n" +
	"\x19supports_memory_snapshots\x18\x04 \x01(\bR\x17supportsMemorySnapshots\x124\n" +
	"\x16supports_linked_clones\x18\x05 \x01(\bR\x14supportsLinkedClones\x122\n" +
	"\x15supports_image_import\x18\x06 \x01(\bR\x13supportsImageImport\x120\n" +
	"\x14supported_disk_types\x18\a \x03(\tR\x12supportedDiskTypes\x126\n" +
	"\x17supported_network_types\x18\b \x03(\tR\x15supportedNetworkTypes*[\n" +
	"\aPowerOp\x12\x18\n" +
	"\x14POWER_OP_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vPOWER_OP_ON\x10\x01\x12\x10\n" +
	"\fPOWER_OP_OFF\x10\x02\x12\x13\n" +
	"\x0fPOWER_OP_REBOOT\x10\x032\xe1\a\n" +
	"\bProvider\x12G\n" +
	"\bValidate\x12\x1c.provider.v1.ValidateRequest\x1a\x1d.provider.v1.ValidateResponse\x12A\n" +
	"\x06Create\x12\x1a.provider.v1.CreateRequest\x1a\x1b.provider.v1.CreateResponse\x12?\n" +
	"\x06Delete\x12\x1a.provider.v1.DeleteRequest\x1a\x19.provider.v1.TaskResponse\x12=\n" +
	"\x05Power\x12\x19.provider.v1.PowerRequest\x1a\x19.provider.v1.TaskResponse\x12I\n" +
	"\vReconfigure\x12\x1f.provider.v1.ReconfigureRequest\x1a\x19.provider.v1.TaskResponse\x12G\n" +
	"\bDescribe\x12\x1c.provider.v1.DescribeRequest\x1a\x1d.provider.v1.DescribeResponse\x12M\n" +
	"\n" +
	"TaskStatus\x12\x1e.provider.v1.TaskStatusRequest\x1a\x1f.provider.v1.TaskStatusResponse\x12Y\n" +
	"\x0eSnapshotCreate\x12\".provider.v1.SnapshotCreateRequest\x1a#.provider.v1.SnapshotCreateResponse\x12O\n" +
	"\x0eSnapshotDelete\x12\".provider.v1.SnapshotDeleteRequest\x1a\x19.provider.v1.TaskResponse\x12O\n" +
	"\x0eSnapshotRevert\x12\".provider.v1.SnapshotRevertRequest\x1a\x19.provider.v1.TaskResponse\x12>\n" +
	"\x05Clone\x12\x19.provider.v1.CloneRequest\x1a\x1a.provider.v1.CloneResponse\x12K\n" +
	"\fImagePrepare\x12 .provider.v1.ImagePrepareRequest\x1a\x19.provider.v1.TaskResponse\x12\\\n" +
	"\x0fGetCapabilities\x12#.provider.v1.GetCapabilitiesRequest\x1a$.provider.v1.GetCapabilitiesResponseBIZGgithub.com/projectbeskar/virtrigaud/internal/rpc/provider/v1;providerv1b\x06proto3"

var (
	file_provider_v1_provider_proto_rawDescOnce sync.Once
	file_provider_v1_provider_proto_rawDescData []byte
)

func file_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)))
	})
	return file_provider_v1_provider_proto_rawDescData
}

var file_provider_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_provider_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_provider_v1_provider_proto_goTypes = []any{
	(PowerOp)(0),                    // 0: provider.v1.PowerOp
	(*TaskRef)(nil),                 // 1: provider.v1.TaskRef
	(*Empty)(nil),                   // 2: provider.v1.Empty
	(*ValidateRequest)(nil),         // 3: provider.v1.ValidateRequest
	(*ValidateResponse)(nil),        // 4: provider.v1.ValidateResponse
	(*CreateRequest)(nil),           // 5: provider.v1.CreateRequest
	(*CreateResponse)(nil),          // 6: provider.v1.CreateResponse
	(*DeleteRequest)(nil),           // 7: provider.v1.DeleteRequest
	(*PowerRequest)(nil),            // 8: provider.v1.PowerRequest
	(*ReconfigureRequest)(nil),      // 9: provider.v1.ReconfigureRequest
	(*TaskResponse)(nil),            // 10: provider.v1.TaskResponse
	(*DescribeRequest)(nil),         // 11: provider.v1.DescribeRequest
	(*DescribeResponse)(nil),        // 12: provider.v1.DescribeResponse
	(*TaskStatusRequest)(nil),       // 13: provider.v1.TaskStatusRequest
	(*TaskStatusResponse)(nil),      // 14: provider.v1.TaskStatusResponse
	(*SnapshotCreateRequest)(nil),   // 15: provider.v1.SnapshotCreateRequest
	(*SnapshotCreateResponse)(nil),  // 16: provider.v1.SnapshotCreateResponse
	(*SnapshotDeleteRequest)(nil),   // 17: provider.v1.SnapshotDeleteRequest
	(*SnapshotRevertRequest)(nil),   // 18: provider.v1.SnapshotRevertRequest
	(*CloneRequest)(nil),            // 19: provider.v1.CloneRequest
	(*CloneResponse)(nil),           // 20: provider.v1.CloneResponse
	(*ImagePrepareRequest)(nil),     // 21: provider.v1.ImagePrepareRequest
	(*GetCapabilitiesRequest)(nil),  // 22: provider.v1.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil), // 23: provider.v1.GetCapabilitiesResponse
}
var file_provider_v1_provider_proto_depIdxs = []int32{
	1,  // 0: provider.v1.CreateResponse.task:type_name -> provider.v1.TaskRef
	0,  // 1: provider.v1.PowerRequest.op:type_name -> provider.v1.PowerOp
	1,  // 2: provider.v1.TaskResponse.task:type_name -> provider.v1.TaskRef
	1,  // 3: provider.v1.TaskStatusRequest.task:type_name -> provider.v1.TaskRef
	1,  // 4: provider.v1.SnapshotCreateResponse.task:type_name -> provider.v1.TaskRef
	1,  // 5: provider.v1.CloneResponse.task:type_name -> provider.v1.TaskRef
	3,  // 6: provider.v1.Provider.Validate:input_type -> provider.v1.ValidateRequest
	5,  // 7: provider.v1.Provider.Create:input_type -> provider.v1.CreateRequest
	7,  // 8: provider.v1.Provider.Delete:input_type -> provider.v1.DeleteRequest
	8,  // 9: provider.v1.Provider.Power:input_type -> provider.v1.PowerRequest
	9,  // 10: provider.v1.Provider.Reconfigure:input_type -> provider.v1.ReconfigureRequest
	11, // 11: provider.v1.Provider.Describe:input_type -> provider.v1.DescribeRequest
	13, // 12: provider.v1.Provider.TaskStatus:input_type -> provider.v1.TaskStatusRequest
	15, // 13: provider.v1.Provider.SnapshotCreate:input_type -> provider.v1.SnapshotCreateRequest
	17, // 14: provider.v1.Provider.SnapshotDelete:input_type -> provider.v1.SnapshotDeleteRequest
	18, // 15: provider.v1.Provider.SnapshotRevert:input_type -> provider.v1.SnapshotRevertRequest
	19, // 16: provider.v1.Provider.Clone:input_type -> provider.v1.CloneRequest
	21, // 17: provider.v1.Provider.ImagePrepare:input_type -> provider.v1.ImagePrepareRequest
	22, // 18: provider.v1.Provider.GetCapabilities:input_type -> provider.v1.GetCapabilitiesRequest
	4,  // 19: provider.v1.Provider.Validate:output_type -> provider.v1.ValidateResponse
	6,  // 20: provider.v1.Provider.Create:output_type -> provider.v1.CreateResponse
	10, // 21: provider.v1.Provider.Delete:output_type -> provider.v1.TaskResponse
	10, // 22: provider.v1.Provider.Power:output_type -> provider.v1.TaskResponse
	10, // 23: provider.v1.Provider.Reconfigure:output_type -> provider.v1.TaskResponse
	12, // 24: provider.v1.Provider.Describe:output_type -> provider.v1.DescribeResponse
	14, // 25: provider.v1.Provider.TaskStatus:output_type -> provider.v1.TaskStatusResponse
	16, // 26: provider.v1.Provider.SnapshotCreate:output_type -> provider.v1.SnapshotCreateResponse
	10, // 27: provider.v1.Provider.SnapshotDelete:output_type -> provider.v1.TaskResponse
	10, // 28: provider.v1.Provider.SnapshotRevert:output_type -> provider.v1.TaskResponse
	20, // 29: provider.v1.Provider.Clone:output_type -> provider.v1.CloneResponse
	10, // 30: provider.v1.Provider.ImagePrepare:output_type -> provider.v1.TaskResponse
	23, // 31: provider.v1.Provider.GetCapabilities:output_type -> provider.v1.GetCapabilitiesResponse
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_provider_v1_provider_proto_init() }
func file_provider_v1_provider_proto_init() {
	if File_provider_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_provider_v1_provider_proto_depIdxs,
		EnumInfos:         file_provider_v1_provider_proto_enumTypes,
		MessageInfos:      file_provider_v1_provider_proto_msgTypes,
	}.Build()
	File_provider_v1_provider_proto = out.File
	file_provider_v1_provider_proto_goTypes = nil
	file_provider_v1_provider_proto_depIdxs = nil
}
