// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: provider/v1/provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Power operations enum
type PowerOp int32

const (
	PowerOp_POWER_OP_UNSPECIFIED PowerOp = 0
	PowerOp_POWER_OP_ON          PowerOp = 1
	PowerOp_POWER_OP_OFF         PowerOp = 2
	PowerOp_POWER_OP_REBOOT      PowerOp = 3
)

// Enum value maps for PowerOp.
var (
	PowerOp_name = map[int32]string{
		0: "POWER_OP_UNSPECIFIED",
		1: "POWER_OP_ON",
		2: "POWER_OP_OFF",
		3: "POWER_OP_REBOOT",
	}
	PowerOp_value = map[string]int32{
		"POWER_OP_UNSPECIFIED": 0,
		"POWER_OP_ON":          1,
		"POWER_OP_OFF":         2,
		"POWER_OP_REBOOT":      3,
	}
)

func (x PowerOp) Enum() *PowerOp {
	p := new(PowerOp)
	*p = x
	return p
}

func (x PowerOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerOp) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[0].Descriptor()
}

func (PowerOp) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[0]
}

func (x PowerOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerOp.Descriptor instead.
func (PowerOp) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

// Task reference for async operations
type TaskRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRef) Reset() {
	*x = TaskRef{}
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRef) ProtoMessage() {}

func (x *TaskRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRef.ProtoReflect.Descriptor instead.
func (*TaskRef) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Empty message for operations with no parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

// Validate provider connectivity and configuration
type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Create a new virtual machine
type CreateRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserData []byte                 `protobuf:"bytes,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"` // Already rendered cloud-init/ignition data
	// JSON-encoded provider-agnostic specifications
	ClassJson     string   `protobuf:"bytes,3,opt,name=class_json,json=classJson,proto3" json:"class_json,omitempty"`             // VMClass
	ImageJson     string   `protobuf:"bytes,4,opt,name=image_json,json=imageJson,proto3" json:"image_json,omitempty"`             // VMImage
	NetworksJson  string   `protobuf:"bytes,5,opt,name=networks_json,json=networksJson,proto3" json:"networks_json,omitempty"`    // []NetworkAttachment
	DisksJson     string   `protobuf:"bytes,6,opt,name=disks_json,json=disksJson,proto3" json:"disks_json,omitempty"`             // []DiskSpec
	PlacementJson string   `protobuf:"bytes,7,opt,name=placement_json,json=placementJson,proto3" json:"placement_json,omitempty"` // Placement
	Tags          []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`                                        // Tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetUserData() []byte {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *CreateRequest) GetClassJson() string {
	if x != nil {
		return x.ClassJson
	}
	return ""
}

func (x *CreateRequest) GetImageJson() string {
	if x != nil {
		return x.ImageJson
	}
	return ""
}

func (x *CreateRequest) GetNetworksJson() string {
	if x != nil {
		return x.NetworksJson
	}
	return ""
}

func (x *CreateRequest) GetDisksJson() string {
	if x != nil {
		return x.DisksJson
	}
	return ""
}

func (x *CreateRequest) GetPlacementJson() string {
	if x != nil {
		return x.PlacementJson
	}
	return ""
}

func (x *CreateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // Provider-specific VM identifier
	Task          *TaskRef               `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"` // Optional task reference for async operations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateResponse) GetTask() *TaskRef {
	if x != nil {
		return x.Task
	}
	return nil
}

// Delete a virtual machine
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Power control operations
type PowerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Op            PowerOp                `protobuf:"varint,2,opt,name=op,proto3,enum=provider.v1.PowerOp" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerRequest) Reset() {
	*x = PowerRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerRequest) ProtoMessage() {}

func (x *PowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerRequest.ProtoReflect.Descriptor instead.
func (*PowerRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *PowerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PowerRequest) GetOp() PowerOp {
	if x != nil {
		return x.Op
	}
	return PowerOp_POWER_OP_UNSPECIFIED
}

// Reconfigure virtual machine resources
type ReconfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DesiredJson   string                 `protobuf:"bytes,2,opt,name=desired_json,json=desiredJson,proto3" json:"desired_json,omitempty"` // JSON-encoded desired state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconfigureRequest) Reset() {
	*x = ReconfigureRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconfigureRequest) ProtoMessage() {}

func (x *ReconfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconfigureRequest.ProtoReflect.Descriptor instead.
func (*ReconfigureRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ReconfigureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReconfigureRequest) GetDesiredJson() string {
	if x != nil {
		return x.DesiredJson
	}
	return ""
}

// Generic task response for async operations
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskRef               `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *TaskResponse) GetTask() *TaskRef {
	if x != nil {
		return x.Task
	}
	return nil
}

// Describe virtual machine current state
type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *DescribeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DescribeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Exists          bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	PowerState      string                 `protobuf:"bytes,2,opt,name=power_state,json=powerState,proto3" json:"power_state,omitempty"`
	Ips             []string               `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
	ConsoleUrl      string                 `protobuf:"bytes,4,opt,name=console_url,json=consoleUrl,proto3" json:"console_url,omitempty"`
	ProviderRawJson string                 `protobuf:"bytes,5,opt,name=provider_raw_json,json=providerRawJson,proto3" json:"provider_raw_json,omitempty"` // Provider-specific additional data
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *DescribeResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *DescribeResponse) GetPowerState() string {
	if x != nil {
		return x.PowerState
	}
	return ""
}

func (x *DescribeResponse) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *DescribeResponse) GetConsoleUrl() string {
	if x != nil {
		return x.ConsoleUrl
	}
	return ""
}

func (x *DescribeResponse) GetProviderRawJson() string {
	if x != nil {
		return x.ProviderRawJson
	}
	return ""
}

// Check async task status
type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskRef               `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *TaskStatusRequest) GetTask() *TaskRef {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message if task failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{13}
}

func (x *TaskStatusResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *TaskStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_provider_v1_provider_proto protoreflect.FileDescriptor

const file_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1aprovider/v1/provider.proto\x12\vprovider.v1\"\x19\n" +
	"\aTaskRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty\"\x11\n" +
	"\x0fValidateRequest\"<\n" +
	"\x10ValidateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfd\x01\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tuser_data\x18\x02 \x01(\fR\buserData\x12\x1d\n" +
	"\n" +
	"class_json\x18\x03 \x01(\tR\tclassJson\x12\x1d\n" +
	"\n" +
	"image_json\x18\x04 \x01(\tR\timageJson\x12#\n" +
	"\rnetworks_json\x18\x05 \x01(\tR\fnetworksJson\x12\x1d\n" +
	"\n" +
	"disks_json\x18\x06 \x01(\tR\tdisksJson\x12%\n" +
	"\x0eplacement_json\x18\a \x01(\tR\rplacementJson\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\"J\n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04task\x18\x02 \x01(\v2\x14.provider.v1.TaskRefR\x04task\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\fPowerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x02op\x18\x02 \x01(\x0e2\x14.provider.v1.PowerOpR\x02op\"G\n" +
	"\x12ReconfigureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdesired_json\x18\x02 \x01(\tR\vdesiredJson\"8\n" +
	"\fTaskResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.provider.v1.TaskRefR\x04task\"!\n" +
	"\x0fDescribeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaa\x01\n" +
	"\x10DescribeResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1f\n" +
	"\vpower_state\x18\x02 \x01(\tR\n" +
	"powerState\x12\x10\n" +
	"\x03ips\x18\x03 \x03(\tR\x03ips\x12\x1f\n" +
	"\vconsole_url\x18\x04 \x01(\tR\n" +
	"consoleUrl\x12*\n" +
	"\x11provider_raw_json\x18\x05 \x01(\tR\x0fproviderRawJson\"=\n" +
	"\x11TaskStatusRequest\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.provider.v1.TaskRefR\x04task\">\n" +
	"\x12TaskStatusResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*[\n" +
	"\aPowerOp\x12\x18\n" +
	"\x14POWER_OP_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vPOWER_OP_ON\x10\x01\x12\x10\n" +
	"\fPOWER_OP_OFF\x10\x02\x12\x13\n" +
	"\x0fPOWER_OP_REBOOT\x10\x032\xf9\x03\n" +
	"\bProvider\x12G\n" +
	"\bValidate\x12\x1c.provider.v1.ValidateRequest\x1a\x1d.provider.v1.ValidateResponse\x12A\n" +
	"\x06Create\x12\x1a.provider.v1.CreateRequest\x1a\x1b.provider.v1.CreateResponse\x12?\n" +
	"\x06Delete\x12\x1a.provider.v1.DeleteRequest\x1a\x19.provider.v1.TaskResponse\x12=\n" +
	"\x05Power\x12\x19.provider.v1.PowerRequest\x1a\x19.provider.v1.TaskResponse\x12I\n" +
	"\vReconfigure\x12\x1f.provider.v1.ReconfigureRequest\x1a\x19.provider.v1.TaskResponse\x12G\n" +
	"\bDescribe\x12\x1c.provider.v1.DescribeRequest\x1a\x1d.provider.v1.DescribeResponse\x12M\n" +
	"\n" +
	"TaskStatus\x12\x1e.provider.v1.TaskStatusRequest\x1a\x1f.provider.v1.TaskStatusResponseBIZGgithub.com/projectbeskar/virtrigaud/internal/rpc/provider/v1;providerv1b\x06proto3"

var (
	file_provider_v1_provider_proto_rawDescOnce sync.Once
	file_provider_v1_provider_proto_rawDescData []byte
)

func file_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)))
	})
	return file_provider_v1_provider_proto_rawDescData
}

var file_provider_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_provider_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_provider_v1_provider_proto_goTypes = []any{
	(PowerOp)(0),               // 0: provider.v1.PowerOp
	(*TaskRef)(nil),            // 1: provider.v1.TaskRef
	(*Empty)(nil),              // 2: provider.v1.Empty
	(*ValidateRequest)(nil),    // 3: provider.v1.ValidateRequest
	(*ValidateResponse)(nil),   // 4: provider.v1.ValidateResponse
	(*CreateRequest)(nil),      // 5: provider.v1.CreateRequest
	(*CreateResponse)(nil),     // 6: provider.v1.CreateResponse
	(*DeleteRequest)(nil),      // 7: provider.v1.DeleteRequest
	(*PowerRequest)(nil),       // 8: provider.v1.PowerRequest
	(*ReconfigureRequest)(nil), // 9: provider.v1.ReconfigureRequest
	(*TaskResponse)(nil),       // 10: provider.v1.TaskResponse
	(*DescribeRequest)(nil),    // 11: provider.v1.DescribeRequest
	(*DescribeResponse)(nil),   // 12: provider.v1.DescribeResponse
	(*TaskStatusRequest)(nil),  // 13: provider.v1.TaskStatusRequest
	(*TaskStatusResponse)(nil), // 14: provider.v1.TaskStatusResponse
}
var file_provider_v1_provider_proto_depIdxs = []int32{
	1,  // 0: provider.v1.CreateResponse.task:type_name -> provider.v1.TaskRef
	0,  // 1: provider.v1.PowerRequest.op:type_name -> provider.v1.PowerOp
	1,  // 2: provider.v1.TaskResponse.task:type_name -> provider.v1.TaskRef
	1,  // 3: provider.v1.TaskStatusRequest.task:type_name -> provider.v1.TaskRef
	3,  // 4: provider.v1.Provider.Validate:input_type -> provider.v1.ValidateRequest
	5,  // 5: provider.v1.Provider.Create:input_type -> provider.v1.CreateRequest
	7,  // 6: provider.v1.Provider.Delete:input_type -> provider.v1.DeleteRequest
	8,  // 7: provider.v1.Provider.Power:input_type -> provider.v1.PowerRequest
	9,  // 8: provider.v1.Provider.Reconfigure:input_type -> provider.v1.ReconfigureRequest
	11, // 9: provider.v1.Provider.Describe:input_type -> provider.v1.DescribeRequest
	13, // 10: provider.v1.Provider.TaskStatus:input_type -> provider.v1.TaskStatusRequest
	4,  // 11: provider.v1.Provider.Validate:output_type -> provider.v1.ValidateResponse
	6,  // 12: provider.v1.Provider.Create:output_type -> provider.v1.CreateResponse
	10, // 13: provider.v1.Provider.Delete:output_type -> provider.v1.TaskResponse
	10, // 14: provider.v1.Provider.Power:output_type -> provider.v1.TaskResponse
	10, // 15: provider.v1.Provider.Reconfigure:output_type -> provider.v1.TaskResponse
	12, // 16: provider.v1.Provider.Describe:output_type -> provider.v1.DescribeResponse
	14, // 17: provider.v1.Provider.TaskStatus:output_type -> provider.v1.TaskStatusResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_provider_v1_provider_proto_init() }
func file_provider_v1_provider_proto_init() {
	if File_provider_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_provider_v1_provider_proto_depIdxs,
		EnumInfos:         file_provider_v1_provider_proto_enumTypes,
		MessageInfos:      file_provider_v1_provider_proto_msgTypes,
	}.Build()
	File_provider_v1_provider_proto = out.File
	file_provider_v1_provider_proto_goTypes = nil
	file_provider_v1_provider_proto_depIdxs = nil
}
