name: Helm CRD Installation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'charts/**'
      - 'config/crd/**'
      - '.github/workflows/helm-crds.yml'
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - 'config/crd/**'
      - '.github/workflows/helm-crds.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GO_VERSION: '1.23'

jobs:
  helm-crd-install-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    name: Helm CRD Install Check
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Set up Kind cluster
      uses: helm/kind-action@v1
      with:
        version: v0.24.0
        cluster_name: virtrigaud-helm-test
        wait: 60s
        verbosity: 1

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: 'latest'

    - name: Install virtrigaud chart (CRDs included)
      run: |
        helm install virtrigaud charts/virtrigaud \
          --wait \
          --timeout 5m \
          --set manager.image.repository=test \
          --set manager.image.tag=test \
          --dry-run=false

    - name: Verify CRDs were installed
      run: |
        kubectl get crd virtualmachines.infra.virtrigaud.io -o yaml | grep "conversion:" || {
          echo "Error: VirtualMachine CRD missing conversion webhook"
          exit 1
        }
        
        kubectl get crd providers.infra.virtrigaud.io -o yaml | grep "conversion:" || {
          echo "Error: Provider CRD missing conversion webhook"
          exit 1
        }

    - name: Verify conversion webhook configuration
      run: |
        # Check that conversion webhook path is /convert as required
        WEBHOOK_PATH=$(kubectl get crd virtualmachines.infra.virtrigaud.io -o jsonpath='{.spec.conversion.webhook.clientConfig.service.path}')
        if [ "$WEBHOOK_PATH" != "/convert" ]; then
          echo "Error: Expected webhook path '/convert', got '$WEBHOOK_PATH'"
          exit 1
        fi
        echo "✅ Conversion webhook path correctly set to: $WEBHOOK_PATH"
        
        # Verify webhook service configuration
        SERVICE_NAME=$(kubectl get crd virtualmachines.infra.virtrigaud.io -o jsonpath='{.spec.conversion.webhook.clientConfig.service.name}')
        SERVICE_NAMESPACE=$(kubectl get crd virtualmachines.infra.virtrigaud.io -o jsonpath='{.spec.conversion.webhook.clientConfig.service.namespace}')
        echo "✅ Webhook service: $SERVICE_NAME in namespace $SERVICE_NAMESPACE"

    - name: Check CRD versions
      run: |
        echo "Checking CRD versions..."
        for crd in virtualmachines providers vmclasses vmimages vmnetworkattachments vmsnapshots vmclones vmsets vmplacementpolicies; do
          echo "=== $crd.infra.virtrigaud.io ==="
          kubectl get crd ${crd}.infra.virtrigaud.io -o jsonpath='{.spec.versions[*].name}' | tr ' ' '\n' | sort
          echo ""
        done

    - name: Test --skip-crds installation path
      run: |
        echo "Testing Helm install with --skip-crds flag"
        # First uninstall the chart but keep CRDs
        helm uninstall virtrigaud
        sleep 5
        
        # Verify CRDs are still present
        kubectl get crd virtualmachines.infra.virtrigaud.io || {
          echo "Error: CRDs were unexpectedly deleted"
          exit 1
        }
        
        # Now install with --skip-crds (should work since CRDs already exist)
        helm install virtrigaud charts/virtrigaud \
          --skip-crds \
          --wait \
          --timeout 5m \
          --set manager.image.repository=test \
          --set manager.image.tag=test
        
        echo "✅ Helm install with --skip-crds succeeded"

    - name: Final cleanup
      run: |
        helm uninstall virtrigaud || true
        # Clean up CRDs manually since they persist
        kubectl delete crd virtualmachines.infra.virtrigaud.io || true
        kubectl delete crd providers.infra.virtrigaud.io || true
