name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.21'
  GOLANGCI_LINT_VERSION: 'v1.58.2'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: ${{ env.GOLANGCI_LINT_VERSION }}
        args: --version

    - name: Run golangci-lint
      run: |
        echo "🔍 Running comprehensive linting..."
        make lint-check
        
    - name: Verify no lint issues
      run: |
        echo "✅ All lint checks passed - zero issues found!"
